# Generated by Django 3.2.8 on 2022-09-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=100, verbose_name='Apellido P')),
                ('apellidoM', models.CharField(max_length=100, verbose_name='Apellido M')),
                ('fechaNac', models.TextField(null=True, verbose_name='Fecha Nac')),
                ('correo', models.TextField(null=True, verbose_name='Correo')),
            ],
        ),
    ]
