# Generated by Django 3.2.8 on 2022-09-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='fechaNac',
            field=models.DateField(blank=True, verbose_name='Fecha Nac'),
        ),
    ]
