# Generated by Django 3.2.8 on 2022-10-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0005_auto_20221001_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=100, verbose_name='Apellido P')),
                ('apellidoM', models.CharField(max_length=100, verbose_name='Apellido M')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha Nac (yyyy-mm-dd)')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Correo')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('cuatri', models.IntegerField(verbose_name='Cuatrimestre')),
                ('grupo', models.CharField(max_length=10, verbose_name='Grupo')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
