# Generated by Django 3.2.8 on 2022-10-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0006_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='foto',
        ),
    ]
