# Generated by Django 3.2.8 on 2022-10-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0009_remove_alumno_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(max_length=15, primary_key=True, serialize=False)),
                ('cuatri', models.IntegerField(max_length=100, verbose_name='Cuatrimestre')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('profesor', models.CharField(max_length=100, verbose_name='Profesor')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
            ],
        ),
    ]
