# Generated by Django 3.2.8 on 2022-10-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0012_alter_horario_horaentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
