# Generated by Django 3.2.8 on 2022-10-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0013_alter_horario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='cuatri',
            field=models.IntegerField(verbose_name='Cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
