# Generated by Django 3.2.8 on 2022-10-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0014_auto_20221008_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=100, verbose_name='Apellido P')),
                ('apellidoM', models.CharField(max_length=100, verbose_name='Apellido M')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo')),
            ],
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaEntrada',
            field=models.TimeField(verbose_name='Hora de entrada'),
        ),
    ]
