# Generated by Django 3.2.8 on 2022-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0015_auto_20221009_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estatus',
            field=models.CharField(max_length=100, null=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaEntrada',
            field=models.TimeField(null=True, verbose_name='Hora de entrada'),
        ),
    ]
