# Generated by Django 3.2.8 on 2022-10-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0016_auto_20221009_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estatus',
            field=models.CharField(max_length=100, verbose_name='Estatus'),
        ),
    ]
