# Generated by Django 3.2.8 on 2022-10-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0016_alumno_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
    ]
