# Generated by Django 3.2.8 on 2022-10-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0017_alter_asistencia_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='estatus',
            new_name='status',
        ),
    ]
