# Generated by Django 3.2.8 on 2022-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0018_alter_horario_horaentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaJusti', models.DateField(blank=True, null=True, verbose_name='Fecha de justificante (yyyy-mm-dd)')),
                ('motivo', models.CharField(max_length=100, verbose_name='motivo')),
                ('receta', models.FileField(null=True, upload_to='archivos/', verbose_name='archivo')),
            ],
        ),
    ]
