# Generated by Django 3.2.8 on 2022-10-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0019_justificante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='archivo',
        ),
    ]
