# Generated by Django 3.2.8 on 2022-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0020_remove_alumno_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID_Profesor'),
        ),
    ]
