# Generated by Django 3.2.8 on 2022-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0021_alter_directivo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='apellidoM',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellido M'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Area'),
        ),
    ]
