# Generated by Django 3.2.8 on 2022-10-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0024_auto_20221028_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='profesor',
        ),
    ]
