# Generated by Django 3.2.8 on 2022-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0025_auto_20221028_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='tolerancia',
            field=models.IntegerField(null=True, verbose_name='Tolerancia'),
        ),
    ]
