# Generated by Django 3.2.8 on 2022-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0026_horario_tolerancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='apellidoM',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='apellidoP',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fechaReg',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Reg (yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='matricula',
            field=models.CharField(max_length=100, null=True, verbose_name='Matricula_Alumno'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Status'),
        ),
    ]
