# Generated by Django 3.2.8 on 2022-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0028_justificante_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomUsuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('directivo_id', models.CharField(max_length=15, verbose_name='ID_Directivo')),
                ('profesor_id', models.CharField(max_length=15, verbose_name='ID_Profesor')),
                ('alumno_matricula', models.CharField(max_length=15, verbose_name='Matricula_Alumno')),
            ],
        ),
    ]
