# Generated by Django 3.2.8 on 2022-11-06 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUpemor', '0032_auto_20221105_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='directivo',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='directivo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fechaNac',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Nac (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fechaReg',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Reg (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='fechaNac',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Nac (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='justificante',
            name='fechaJusti',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de justificante (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fechaNac',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Nac (yyyy-mm-dd)'),
        ),
    ]
