# Generated by Django 3.2.8 on 2022-11-06 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUpemor', '0036_alter_directivo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directivo', to=settings.AUTH_USER_MODEL),
        ),
    ]
