# Generated by Django 3.2.8 on 2022-11-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0040_alter_directivo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivo',
            name='user',
        ),
    ]
