# Generated by Django 3.2.8 on 2022-11-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0041_remove_directivo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
