# Generated by Django 3.2.8 on 2022-11-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0046_directivo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='directivo',
            name='userType',
            field=models.CharField(default='Directivo', max_length=100, verbose_name='Tipo de usuario'),
        ),
    ]
