# Generated by Django 3.2.8 on 2022-11-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0048_alter_directivo_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Directivo'),
        ),
    ]
