# Generated by Django 3.2.8 on 2022-11-07 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUpemor', '0049_alter_directivo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(null=True, upload_to='user_profile/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='userType',
            field=models.CharField(default='No', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='apellidoM',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Apellido M'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directivo', to=settings.AUTH_USER_MODEL),
        ),
    ]
