# Generated by Django 3.2.8 on 2022-11-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0050_auto_20221107_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='userType',
            field=models.CharField(default='Directivo', max_length=100, verbose_name=''),
        ),
    ]
