# Generated by Django 3.2.8 on 2022-11-08 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUpemor', '0051_alter_usuario_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido M'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directivo', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tolerancia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tolerancia'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido M'),
        ),
    ]
