# Generated by Django 3.2.8 on 2022-11-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0052_auto_20221108_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='grupo',
        ),
    ]
