# Generated by Django 3.2.8 on 2022-11-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0053_remove_alumno_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='alumno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='AppUpemor.alumno', verbose_name='ID_Alumno'),
        ),
    ]
