# Generated by Django 3.2.8 on 2022-11-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0055_auto_20221109_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='matricula',
        ),
    ]
