# Generated by Django 3.2.8 on 2022-11-09 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUpemor', '0056_remove_asistencia_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnoUser', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesorUser', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario'),
        ),
    ]
