# Generated by Django 3.2.8 on 2022-11-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0057_auto_20221109_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificante',
            name='matricula',
        ),
        migrations.AddField(
            model_name='justificante',
            name='alumno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alumnoJus', to='AppUpemor.alumno', verbose_name='ID_Alumno'),
        ),
    ]
