# Generated by Django 3.2.8 on 2022-11-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0060_grupo_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(max_length=1, verbose_name='Grupo'),
        ),
    ]
