# Generated by Django 3.2.8 on 2022-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0061_alter_grupo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='userDirectivo',
            field=models.BooleanField(default=False),
        ),
    ]
