# Generated by Django 3.2.8 on 2022-11-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0062_usuario_userdirectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='userDirectivo',
            field=models.BooleanField(default=False, verbose_name='Directivo'),
        ),
    ]
