# Generated by Django 3.2.8 on 2022-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0063_alter_usuario_userdirectivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='userDirectivo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='userType',
            field=models.CharField(default='Alumno', max_length=100, verbose_name=''),
        ),
        migrations.AddField(
            model_name='profesor',
            name='userType',
            field=models.CharField(default='Profesor', max_length=100, verbose_name=''),
        ),
    ]
