# Generated by Django 3.2.8 on 2022-11-11 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUpemor', '0064_auto_20221111_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='carrera',
            field=models.CharField(choices=[('ITI', 'Ingeniería en Tecnologías de la Información'), ('IIN', 'Ingeniería Industrial'), ('IBT', 'Ingeniería en Biotecnología'), ('IFI', 'Ingeniería Financiera'), ('LAE', 'Licenciatura en Administración de Empresas')], default='', max_length=3, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
