# Generated by Django 3.2.8 on 2022-11-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0065_auto_20221111_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='carrera',
            field=models.CharField(choices=[('ITI', 'Ingeniería en Tecnologías de la Información'), ('IIN', 'Ingeniería Industrial'), ('IBT', 'Ingeniería en Biotecnología'), ('IFI', 'Ingeniería Financiera'), ('LAE', 'Licenciatura en Administración de Empresas')], default='None', max_length=3, verbose_name='Carrera'),
        ),
    ]
