# Generated by Django 3.2.8 on 2022-11-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0066_alter_grupo_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='carrera',
        ),
    ]
