# Generated by Django 3.2.8 on 2022-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0067_remove_grupo_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='carrera',
            field=models.CharField(default='', max_length=3, verbose_name='Carrera'),
        ),
    ]
