# Generated by Django 3.2.8 on 2022-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0070_auto_20221114_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='status',
            field=models.CharField(default='', max_length=15, verbose_name='estatus'),
        ),
    ]
