# Generated by Django 3.2.8 on 2022-11-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0071_alter_asistencia_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='grupo_id',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='horario_id',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='profesor_id',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grupoAlum', to='AppUpemor.grupo', verbose_name='ID_Grupo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grupoAsig', to='AppUpemor.grupo', verbose_name='ID_Grupo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='horarioAsig', to='AppUpemor.horario', verbose_name='ID_Horario'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profesorAsig', to='AppUpemor.profesor', verbose_name='ID_Profesor'),
        ),
    ]
