# Generated by Django 3.2.8 on 2022-11-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUpemor', '0072_auto_20221116_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='grupo',
            new_name='grupo_id',
        ),
    ]
